sp1232 DPCAPP-234232 asdfasdfasdfafa

diff --git a/.github/workflows/check_commit_message.yml b/.github/workflows/check_commit_message.yml
--- a/.github/workflows/check_commit_message.yml
+++ b/.github/workflows/check_commit_message.yml
@@ -21,6 +21,12 @@ jobs:
       - name: Check commit messages
         id: commit_message
         run: |
-          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"%s")
+          commits=$(git log ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} --pretty=format:"%s" | grep -vE '^Merge branch')
           echo "$commits"
+          if echo "$commits" | grep -Eqv '^sp\d{2,}\s+DPCAPP-\d+\s+.*'; then
+            echo "One or more commit messages do not match the required pattern."
+            echo "$commits" | grep -Ev '^sp\d{2,}\s+DPCAPP-\d+\s+.*'
+            exit 1
+          fi
+          
 
